
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation manual: !include_dir_merge_list automation/
automation ui: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies: 192.168.99.56


homematic:
  interfaces:
    homeaticip:
      host: 192.168.99.59
      resolvenames: json
      port: 2010
      username: Admin
      password: !secret homematic_pw

mqtt:
  discovery: true
  broker: 192.168.99.61
  client_id: home-assistant
  username: ha
  password: !secret mqtt_pw

binary_sensor:
  - platform: workday
    country: DE
    province: BY

input_boolean:
  vacation_mode:
    name: Urlaubsmodus
    initial: off
    icon: mdi:island

emulated_hue:
  listen_port: 80

template:
  sensors:

    roborock_s5_battery:
      friendly_name: 'Roborock S5 Battery'
      value_template: "{{state_attr('vacuum.roborock_vacuum_s5', 'battery_level')}}"
      unit_of_measurement: '%'
      device_class: battery

    roborock_s5_lifetime_cleaned_area:
      friendly_name: 'Lifetime Cleaned Area'
      value_template: "{{state_attr('vacuum.roborock_vacuum_s5', 'total_cleaned_area')}}"
      unit_of_measurement: ㎡

    roborock_s5_lifetime_cleaning_time:
      friendly_name: 'Lifetime Cleaning Time'
      value_template: "{{(state_attr('vacuum.roborock_vacuum_s5', 'total_cleaning_time') / 60)|round(1, 'floor')}}"

    # NOTE: This date is converted to be timezone aware so that it plays nice
    # with some other templating functions and filters.
    roborock_s5_last_cleaned:
      friendly_name: Relative time since last cleaning ended
      value_template: "{{relative_time(strptime(as_timestamp(state_attr('vacuum.roborock_vacuum_s5', 'clean_stop'))|timestamp_custom('%Y-%m-%d %H:%M:%S%z'), '%Y-%m-%d %H:%M:%S%z'))}}"

    roborock_s5_lifetime_cleaning_count:
      friendly_name: 'Lifetime Cleaning Count'
      value_template: "{{state_attr('vacuum.roborock_vacuum_s5', 'cleaning_count')}}"
